services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_securepass
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
    networks:
      - securepass_network

  backend:
    build: .
    container_name: securepass_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./src:/app/src
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - securepass_network

volumes:
  mongodb_data:

networks:
  securepass_network:
    driver: bridge